# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    # Ruby is needed for asciidoctor
    ruby: "3.3"

# Install dependencies for building documentation
python:
  install:
    - requirements: requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build formats
formats:
  - pdf
  - epub
  - htmlzip