# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    # Ruby is needed for asciidoctor
    ruby: "3.1"

# Install dependencies for building documentation
python:
  install:
    - requirements: requirements.txt

# Commands to run before building the docs
commands:
  before_build:
    - gem install asciidoctor
    - gem install asciidoctor-diagram   # Optional: for diagram support
    - gem install rouge                 # Optional: for syntax highlighting
    - pip install sphinx-asciidoc

# Sphinx configuration
sphinx:
  configuration: conf.py
  fail_on_warning: false

# Build formats
formats:
  - pdf
  - epub
  - htmlzip