name: Build specification document

on:
  push:
    branches:
      - dev
      - feature/render-specdoc
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y asciidoctor
      - name: Build docs
        run: |
          asciidoctor docs/*.adoc
          mv docs/README.html docs/specification.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/"

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4